modLoader="javafml"
loaderVersion="[40,)"
license="MIT"
issueTrackerURL="https://github.com/Vonix-Network/everyday-furniture-forge/issues"
[[mods]]
modId="everydayfurniture"
version="1.0.0+1.18.2"
displayName="Everyday Furniture"
authors="Vonix.Network"
description='''Original everyday household furniture with included 3D block models for Forge 1.18.2.'''
[[dependencies.everydayfurniture]]
modId="forge"
mandatory=true
versionRange="[40,)"
ordering="NONE"
side="BOTH"
[[dependencies.everydayfurniture]]
modId="minecraft"
mandatory=true
versionRange="[1.18.2,1.19)"
ordering="NONE"
side="BOTH"
